services:
  node:
    image: tugboatqa/node:10
    
    commands:
      init:
        - npm install --global gatsby-cli
        - gatsby new gatsby-site
        
      build:
        - cd "/gatsby-site" && gatsby build --verbose
        
  nginx:
    image: tugboatqa/nginx:1
    default: true
    depends: node
