services:
  node:
    image: tugboatqa/node:10
    default: true
    
    commands:
      init:
        - npm install --global gatsby-cli
        - gatsby new gatsby-site
        - ln -snf "${TUGBOAT_ROOT}/gatsby-site" "${DOCROOT}"
