services:
  nginx:
    image: tugboatqa/nginx:1
    default: true
    
    commands:
      init:
        # Adding the NodeSource APT repository AND the PGP key for verifying packages
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        # Install Node.js
        - apt-get install -y nodejs
        - npm install npm --global
        
        - npm install --global gatsby-cli
        - gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default#v2
        
      build: 
        - cd "${TUGBOAT_ROOT}/gatsby-site/" && gatsby build --verbose
        - ln -snf "${TUGBOAT_ROOT}/gatsby-site/public" "${DOCROOT}"
 
