services:

  # What to call the default hosting service. This name also acts as the 
  # hostname to access this service by from other services defined in this 
  # config.
  nginx:
    image: tugboatqa/nginx:1
    # Set this as the default service. This does a few things:
    #   1. Clones the git repository into the service container //checkout: true
    #   2. Exposes port 80 to the Tugboat HTTP proxy //expose: 80
    #   3. Routes requests to the preview URL to this service
    default: true
    
    # A set of commands to run while building this service
    # See https://docs.tugboat.qa/configuring-tugboat/#commands for details.
    commands:
    
      # The `init` command is called from two different actions:
      #   1. When a preview is first created: `init`, then `update`, then `build`
      #   2. When a preview is rebuilt: `init`, then `update`, then `build`
      # The `init` command is not called when a preview is cloned or 
      # refreshed.  
      init:
        # Adding the NodeSource APT repository AND the PGP key for verifying packages
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        # Install Node.js
        - apt-get install -y nodejs
        - npm install npm --global
        
        - npm install --global gatsby-cli
        - gatsby new gatsby-site
      
      # The `build` command is called from three different actions:
      #   1. When a preview is first created: `init`, then `update`, then `build`
      #   2. When a preview is created from a base preview: `build`
      #   3. When a preview is refreshed: `update`, then `build`
      # Base Previews provide Tugboat with a starting point, from where it can 
      # build new previews. When a preview is marked as a base preview, 
      # Tugboat preserves the build just after the `init` and `update` steps
      # have run. In this instance, Tugboat will only run the `build` commands 
      # within your services in real time. Base Previews drastically reduce 
      # preview build times and the amount of space a preview occupies on disk.
      # See https://docs.tugboat.qa/concepts/base-previews/ for reference.
      build: 
        - cd "${TUGBOAT_ROOT}/gatsby-site/" && gatsby build --verbose
        - ln -snf "${TUGBOAT_ROOT}/gatsby-site/public" "${DOCROOT}"
 
